### PR TITLE
Add Suggestion For `readded` Mispelling

### PR DESCRIPTION
**Pull request by Casey-Kiewit**

### CODE REVIEW

**Comment by Casey-Kiewit** [comment]
Also interesting to mention is that "readded" is an accepted alternative spelling for "re-added", so arguably it may be more appropriate to drop this misspelling along with "readd".

**Comment by DimitriPapadopoulos** [comment]
We already have:
https://github.com/codespell-project/codespell/blob/fad528e426eef47c019a68fe134e832952bf7e67/codespell_lib/data/dictionary.txt#L30655

**Comment by Casey-Kiewit** [comment]
@DimitriPapadopoulos That's interesting. To better mesh these disparate recommendations, what do you think of updating that entry to recommend `re-added` instead of `readded` to match the recommendation in the other dictionary? If this is the route we want to take, I've pushed that change.

**Comment by DimitriPapadopoulos** [comment]
I can find **`readd`** in the [Collins](https://www.collinsdictionary.com/dictionary/english/readd), but not [Cambridge](https://dictionary.cambridge.org/spellcheck/english/?q=readd), [Oxford Learner's](https://www.oxfordlearnersdictionaries.com/spellcheck/english/?q=readd), [Macmillan](https://www.macmillandictionary.com/spellcheck/british/?q=readd), [Longman](https://www.ldoceonline.com/spellcheck/english/?q=readd), or [Merriam-Webster](https://www.merriam-webster.com/dictionary/readd). I am not 100% certain what maintainers would prefer in this case, but your suggestion looks good to me: change `readd` to `re-add` only in _rare_.

**Comment by DimitriPapadopoulos** [comment]
In that case, I would add all verbal forms in _rare_;
```
readd->re-add, read,
readded->re-added, read,
readding->re-adding, reading,
readds->re-adds, reads,
```

**Comment by Casey-Kiewit** [comment]
@DimitriPapadopoulos I've made the change you recommended. Thanks for you guidance on this!

**Review by DimitriPapadopoulos — APPROVED** [review]

**Comment by vlotorev** [comment]
It looks like `readd` should be preferred for `re-add`. Googling for 'hyphenation for re prefix' returns:

> don’t hyphenate words beginning with re- unless it’s necessary to avoid confusion or re- is followed by a proper noun

Red Hat Technical Writing Style Guide - https://stylepedia.net/style/#hyphenation
Microsoft Writing Style Guide - https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/r/re
This Reddit [comment](https://www.reddit.com/r/grammar/comments/csh89t/comment/exertqa/) mentions the same is recommended by Chicago style, but the style is not publicly available.

**Pull request merged**
