### PR TITLE
Keep GitHub Actions up to date with Dependabot

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Review by peternewman — CHANGES_REQUESTED** [review]
Do you want to synchronise with https://github.com/codespell-project/actions-codespell/blob/master/.github/dependabot.yml so we're consistent across the board (and the comments too)

**Comment by DimitriPapadopoulos** [comment]
I have copied verbatim the example from [Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions).

**Comment by DimitriPapadopoulos** [comment]
But consistency with actions-codespell is OK too. Done.

**Review by peternewman — APPROVED** [review]
LGTM thanks

**Comment by peternewman** [comment]
Thanks, feel free to open some in our other repos too!

**Pull request merged**
