### PR TITLE
Misc queue from 2018 (sorry, lost sources) 

### PR DESCRIPTION
**Pull request by Gelma**

### CODE REVIEW

**Comment by peternewman** [comment]
@larsoner I think this can be merged aside from it now conflicting.

**Comment by larsoner** [comment]
There are tons of PRs that are in a conflicted state. Perhaps we should close them all since they appear to have been programmatically created anyway?

**Comment by Gelma** [comment]
I can fix it one by one.
But the problem is the time going from my upload and the merge.

I can fix it one by one, and you can merge it one by one.

If you wanna close them all, I'm not going to repush them.
It takes a lot of time.

I prefer to work slowly and good, not to follow the anxiety of "empty queue".

Now I fixed this:
https://github.com/codespell-project/codespell/pull/1069

If you commit it, I can close another one. In a few weeks, we can have tons of manual detected errors inside the project.

**Comment by peternewman** [comment]
@Gelma can you fix the conflicts so this can be merged?

**Comment by Gelma** [comment]
> @Gelma can you fix the conflicts so this can be merged?

Yes! I'm going to

**Pull request merged**
