### PR TITLE
Fix more words derived from renable

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Review by skangas — APPROVED** [review]

**Comment by DimitriPapadopoulos** [comment]
@skangas Can you try to re-approve?

**Review by skangas — APPROVED** [review]

**Comment by skangas** [comment]
> @skangas Can you try to re-approve?

Done. Not sure if it changed much, though.

**Comment by DimitriPapadopoulos** [comment]
Indeed, not changed much. Thank you though.

**Review by luzpaz — APPROVED** [review]

**Comment by luzpaz** [comment]
Rebase needed

**Pull request merged**
