### PR TITLE
Disable 'implicity' due to false positives

### PR DESCRIPTION
**Pull request by luzpaz**
Implicity is a [legit word](https://www.merriam-webster.com/dictionary/implicity)

### CODE REVIEW

**Comment by peternewman** [comment]
Can we just remove it from the dictionary then? If we're reluctant to do that, please can you reword the disabled message, `disabled due to common misspelling` implies it is a typo, but it's not, `disabled due to being a valid, but infrequently used word` would be more accurate, but seems daft to me.

**Comment by waldyrious** [comment]
Looking at the existing dictionary, it seems like the usual approach for such potential misspellings is to list both options:

    implicity->implicity, implicitly,

Could that be a solution here?

**Comment by larsoner** [comment]
See also #712, #410, but I guess so

**Comment by peternewman** [comment]
> Could that be a solution here?

I'm personally against that as a user as they still flag up and I have to whitelist them, or disable all of them.

**Comment by waldyrious** [comment]
I see what you mean. My view is that, just like we don't have entries for all possible misspellings of all English words, so we should only add self-correction entries for valid words that are both rare and common misspellings of other words. Since the second criterion is (by definition) more likely to occur than the first one, it sounds like an acceptable trade-off to me.

**Comment by peternewman** [comment]
Surely this should be in rare as part of #1142 ?

**Comment by larsoner** [comment]
Yes I merged these then updated the PR

**Pull request merged**
