### PR TITLE
Typos from marvin.cs.uidaho.edu/misspell.html (rework of #1374): V

### PR DESCRIPTION
**Pull request by bl-ue**
For #1949

### CODE REVIEW

**Review by luzpaz — APPROVED** [review]

**Comment by luzpaz** [comment]
Sucks that github UI does weird things. I fixed the above attempt on my branch. Will submit PR to @bl-ue

**Comment by luzpaz** [comment]
@bl-ue hey I submitted a fix to your repo. Thanks :wink:

**Comment by bl-ue** [comment]
Thank you @luzpuz.  Please feel free to take over these PRs of mine -- I'm not available for OSS right now and for the forseeable future :(

**Comment by luzpaz** [comment]
@bl-ue got it, would be happy to. Would you make an exception in this instance to merge my PR to your repo so the changes reflect here?

**Comment by bl-ue** [comment]
Merged @luzpaz.  I didn't realize that there were PRs on my fork because GitHub doesn't automatically notify me of activity on my forks (which I'm unhappy about).  I merged all of them that don't have conflicts.

FYI - since you have write access to the main codespell repo, you can push commits to any PR's branch, including mine.

**Comment by skangas** [comment]
Could we make some progress with these? I've reviewed this one, and it looks good to me.

**Pull request closed without merging**
