### PR TITLE
Allow words missing from aspell dictionaries

### LINKED ISSUE #2657: Add `donut`, and other words missing from aspell
```
doughnut->donut
doughnuts->donuts
```
Unfortunately, `donut` is missing from the _aspell_ dictionary.
Until it is added to _aspell_ or we modify our CI tests, we cannot add it.

See #2574 and https://github.com/GNUAspell/aspell/issues/628.

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Allowed words are listed in files named using the following scheme:
```
codespell_lib/tests/data/en-additionnal.wordlist
codespell_lib/tests/data/en_GB-additionnal.wordlist
codespell_lib/tests/data/en_US-additionnal.wordlist
```
Prefixes `en`, `en_GB` or `en_US` match one of the supported languages.

We cannot add words with dashes such as `low-colour` or `high-colour` to these lists, _aspell_ doesn't allow that.

Fixes #2657, partially since we cannot add `low-colour` or `high-colour`.

Alternative to #1485.

Adds missing words from #2574.

### CODE REVIEW

**Review by luzpaz — APPROVED** [review]

**Comment by DimitriPapadopoulos** [comment]
Note that I have **not**:
- enforced sorting word lists under `tests/data`,
-  made sure these words appear as fixes in some dictionary,
- made sure these words are flagged as errors by the version of `aspell` run by CI.

This is an alternative to https://github.com/codespell-project/codespell/pull/1485.

**Comment by DimitriPapadopoulos** [comment]
@luzpaz Would you agree with this PR, despite the few shortcomings described above in https://github.com/codespell-project/codespell/pull/2933#issuecomment-1627800169 (mainly lack of testing of the tests themselves)?

**Comment by DimitriPapadopoulos** [comment]
It occurs to me the words may be missing because we don't specify the **size** of the dictionary. The default size is 60 on a scale from 10 to 90. From the [_aspell_ man page](http://aspell.net/man-html/The-Options.html#Dictionary-Options):
> **size**
> 
> (string) The preferred size of the word list. This consists of a two char digit code describing the size of the list, with typical values of: 10=tiny, 20=really small, 30=small, 40=med-small, 50=med, 60=med-large, 70=large, 80=huge, 90=insane.

It would be worth trying 80.

It is nevertheless puzzling that `donuts` is in the med-large dictionary, but not `donut`. I guess the frequency of a word in the different corpora use by [wordlist](https://github.com/en-wl/wordlist) probably decides which dictionaries it ends up in. I am not a native speaker, but I have noticed that characters in American police movies like to eat many `donuts`, not a single `donut`. That might explain the apparent discrepancy.

**Review by larsoner — APPROVED** [review]
Okay with me

**Comment by DimitriPapadopoulos** [comment]
Let me try changing the size of the `aspell` dictionary first. It has to help.

**Comment by DimitriPapadopoulos** [comment]
Unfortunately, changing the _aspell_ dictionary size didn't help. It appears some words are indeed missing from the _aspell_ dictionary, such as `donut` but not `donuts`. See https://github.com/GNUAspell/aspell/issues/628 and https://github.com/en-wl/wordlist/issues/310.

**Comment by DimitriPapadopoulos** [comment]
Part of the missing words have been added to recent _aspell_ directories, sepcificially **2020.12.07**, [available on Debian](https://packages.debian.org/search?suite=default&section=all&arch=any&keywords=aspell-en) but [not available on Ubuntu](https://packages.ubuntu.com/search?keywords=aspell-en):
|               | en_GB | en_US |
|---------------|:-----:|:-----:|
| aesthetic     |   ✓   |   ✓   |
| aesthetically |   ✓   |   ✓   |
| aesthetics    |   ✓   |   ✓   |
| manoeuvred    |   ✓   |       |
| manoeuvring   |   ✓   |       |
| sanitisers    |   ✓   |       |
| sanitizers    |       |   ✓   |
| uninitialised |   ✓   |       |
| uninitialized |       |   ✓   |

Perhaps we should install the most recent aspell-en dictionaries in CI runners.

**Pull request merged**
