### PR TITLE
Add spelling correction for 'prodive'

### PR DESCRIPTION
**Pull request by adrien-berchet**
https://github.com/search?q=prodive&type=code => 6.4K hits
https://github.com/search?q=prodived&type=code => 836 hits

### CODE REVIEW

**Review by DimitriPapadopoulos — APPROVED** [review]

**Review by DimitriPapadopoulos — CHANGES_REQUESTED** [review]
Perhaps add all verbal forms
```
prodives->provides
prodiving->providing
```
as well as:
```
prodiver->provider, pro diver,
prodivers->providers, pro divers,

**Comment by adrien-berchet** [comment]
I added several forms.
For the `pro diving` forms I'm not sure it is relevant because it is a very specific context and it will make codespell to switch to multiple choice mode which, IMO, is more cumbersome to use. But I will add it if you think it's better.

**Review by DimitriPapadopoulos — APPROVED** [review]
I followed the links to GitHub and all typos in source code seem to unequivocally need to be fixed to `provide`, never to `pro dive`. Let's give it a try like this.

**Comment by adrien-berchet** [comment]
Ok, cool. I let you merge then.
Thanks for the review!

**Pull request merged**
