### PR TITLE
Add disporve->disprove and friends

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by vikivivi** [comment]
@peternewman I know this might be a bit too much for you. But would you like to add these additional friends? :)
```text
apporval->approval
apporve->approve
apporved->approved
apporves->approves
apporving->approving

disapporval->disapproval
disapporve->disapprove
disapporved->disapproved
disapporves->disapproves
disapporving->disapproving

porve->prove
porved->proved
porven->proven
porving->proving
porves->proves
```

  * https://github.com/search?q=apporval&type=code
  * https://github.com/search?q=apporve&type=code
  * https://github.com/search?q=apporved&type=code
  * https://github.com/search?q=apporves&type=code
  * https://github.com/search?q=apporving&type=code
  * https://github.com/search?q=disapporval&type=code
  * https://github.com/search?q=disapporve&type=code
  * https://github.com/search?q=disapporved&type=code
  * https://github.com/search?q=disapporves&type=code
  * https://github.com/search?q=disapporving&type=code
  * https://github.com/search?q=porve&type=code
  * https://github.com/search?q=porved&type=code
  * https://github.com/search?q=porven&type=code
  * https://github.com/search?q=porves&type=code
  * https://github.com/search?q=porving&type=code

**Review by luzpaz — APPROVED** [review]

**Comment by vikivivi** [comment]
LGTM. Ignore my above suggestion.

**Comment by luzpaz** [comment]
@vikivivi feel free to add a PR with these suggestions

**Comment by peternewman** [comment]
@vikivivi has opened #2328 to add them...

**Pull request merged**
