### PR TITLE
Fix uncaught exception on empty files

### LINKED ISSUE #2194: codespell fails with uncaught exception on empty files
```sh
$ mkdir -p foo
$ touch foo/bar.sql
$ cd foo
$ 
$ codespell
Traceback (most recent call last):
  File "/home/username/.local/bin/codespell", line 11, in <module>
    load_entry_point('codespell', 'console_scripts', 'codespell')()
  File "/my/path/codespell/codespell_lib/_codespell.py", line 754, in _script_main
    return main(*sys.argv[1:])
  File "/my/path/codespell/codespell_lib/_codespell.py", line 905, in main
    bad_count += parse_file(
  File "/my/path/codespell/codespell_lib/_codespell.py", line 642, in parse_file
    lines, encoding = file_opener.open(filename)
  File "/my/path/codespell/codespell_lib/_codespell.py", line 174, in open
    return self.open_with_internal(filename)
  File "/my/path/codespell/codespell_lib/_codespell.py", line 223, in open_with_internal
    raise Exception('Unknown encoding: %s' % filename)
Exception: Unknown encoding
$ 
```

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Fixes #2194.

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
I have a hard time providing a file with an encoding that wouldn't be flagged as binary and couldn't be loaded as either `utf-8` or `iso-8859-1`. Therefore, I am unable to test the code path where the encoding is neither `utf-8` nor `iso-8859-1`.

**Comment by DimitriPapadopoulos** [comment]
Just understood why everything was being detected as `utf-8`. The initial code was trying to detect encoding errors (in the form of a [`UnicodeDecodeError`](https://docs.python.org/3/library/exceptions.html#UnicodeDecodeError) exception) in `codecs.open(filename, 'r', encoding=encoding)`, which of course won't throw because no data has been read at this point, instead of `f.readlines()`. Fixed that bug as well!

**Comment by DimitriPapadopoulos** [comment]
Tests after fixing encoding detection:
* Detected as binary:
  * `UTF-32`
  * `UCS-2`
  * `UTF-16`
* Detected as `UTF-8`:
  * `UTF-7`
  * `UTF-8`
* Detected as `ISO-8859-1`:
  * `ISO-8859-1`
  *  `ISO-8859-7`
  * `WINDOWS-1253`
  * `WINDOWS-1255`

**Comment by DimitriPapadopoulos** [comment]
We need to address this PR #2195, then I can rebase #2196 so that it gets fixed too.

@peternewman Not sure I understand the [codecov/patch](https://app.codecov.io/gh/codespell-project/codespell/compare/2195/diff#D1L205) alert. What is missing to pass the tests? I haven't removed tests or added functionality.

**Comment by DimitriPapadopoulos** [comment]
Any chance this gets merged?

**Comment by DimitriPapadopoulos** [comment]
@luzpaz This fix is required by #2196.

**Comment by larsoner** [comment]
Thanks @DimitriPapadopoulos

**Pull request merged**
