### PR TITLE
typos found in iperf

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
See https://github.com/esnet/iperf/pull/1350.

### CODE REVIEW

**Review by vikivivi — APPROVED** [review]
LGTM

**Comment by luzpaz** [comment]
i think `sockt` would give **way** too many false positives. Also why is the PR summary have 'relavent' in it?

**Comment by DimitriPapadopoulos** [comment]
`relavant` because it was initially missing,  I guess it disappeared after a rebase.

I agree `sockt` might raise many alerts in existing code, but would they be false positives. I mean, why use `sockt` instead of `socket` in actual code?

**Comment by skangas** [comment]
> I agree `sockt` might raise many alerts in existing code, but would they be false positives? I mean, why use `sockt` instead of `socket` in actual code?

I took a look at [DuckDuckGo](https://html.duckduckgo.com/html/?q=%22sockt%22&norw=1) and [GitHub search](https://github.com/search?q=sockt&type=code), and AFAICT the instances of "sockt" that were found should indeed have been spelled "socket". If we want to be extremely careful, this could of course go to the code dictionary instead. But I'd personally only do that later, if it turns out that users are very unhappy about this change for some reason. So I think this should go in.

Just my two cents.

**Review by skangas — APPROVED** [review]

**Comment by luzpaz** [comment]
Alright, lets see what happens.

**Review by luzpaz — APPROVED** [review]

**Review by luzpaz — CHANGES_REQUESTED** [review]
2nd thought, i think it should go in the code dict. 
I did a github code search and `sockt` is popular in C code. I'd rather stay on the safe side.

**Comment by DimitriPapadopoulos** [comment]
The question is whether it is a library function, the name of which cannot be changed, or a local variable name which would actually qualify as a typo.

That said, `socket` is a POSIX function name, which probably explains why programmers use alternative spellings.

**Review by luzpaz — APPROVED** [review]

**Pull request merged**
