### PR TITLE
Create-Symmetric-Tree.py

### PR DESCRIPTION
**Pull request by deadly-codes**

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
@deadly-codes This is really getting **annoying**.

**Comment by deadly-codes** [comment]
My bad ! I got confused :(

**Comment by luzpaz** [comment]
@deadly-codes confused how? Is there another repository you were intending to submit to ?

**Comment by deadly-codes** [comment]
@DimitriPapadopoulos it was not showing me "merge pull request" and showing me ❌ sign , so i closed it.

**Comment by luzpaz** [comment]
@deadly-codes will you please make more sense? Where were you trying to contribute this code to ?

**Pull request closed without merging**
