### PR TITLE
Add `arragne->arrange` typo

### PR DESCRIPTION
**Pull request by korverdev**
Added typo and variants.

### CODE REVIEW

**Review by DimitriPapadopoulos — APPROVED** [review]

**Review by DimitriPapadopoulos — COMMENTED** [review]
I wonder whether it could be a misspelling of `arraign`.

**Comment by korverdev** [comment]
@DimitriPapadopoulos It's an interesting question. This misspelling is one variant away from `arrange` and two from `arraign`, so I think it's much more likely to be a misspelling of `arrange`. Is there a set standard for this project on how "close" corrections should be from their misspellings?

**Comment by DimitriPapadopoulos** [comment]
No standard. Actually, the standard could be the existence of typos out there. Also, the dictionaries are not only about typos, but any kind of misspelling. I believe non-native speakers may confuse `arraign` and `arragne` on a phonetic basis.

**Comment by DimitriPapadopoulos** [comment]
Thank you @korverdev.

**Pull request merged**
