### PR TITLE
Dict: Add plural of comma

### PR DESCRIPTION
**Pull request by sebweb3r**
Hey, 
I'm not sure about this one. Wiktionary proposes commata as plural of comma[1]. cambridge[2] and aspell[3] don't know commata. 

What is the opinion of our natives? @peternewman @lurch 

[1] https://en.wiktionary.org/wiki/commata
[2] https://dictionary.cambridge.org/us/spellcheck/english/?q=commata
[3] http://app.aspell.net/lookup?dict=en_US;words=commata

### CODE REVIEW

**Comment by lurch** [comment]
I've _never_ heard of "commata" before, and a quick search finds https://english.stackexchange.com/questions/151257/usage-of-commas-vs-commata
:wink:

**Comment by sebweb3r** [comment]
okay, thats what I found too. :-)

**Review by peternewman — CHANGES_REQUESTED** [review]
Grep.app also finds commatas!

I think this should go in usage or rare though, it's not technically a spelling mistake from the looks of things, just a native speaker wouldn't use it.

**Comment by sebweb3r** [comment]
But commatas would be double plural :smile:

**Pull request merged**
