### PR TITLE
Typos in Wordpress History Part 1 of 3

### PR DESCRIPTION
**Pull request by luzpaz**
This PR is an attempt to make the review and merge of @gelma's #1086 PR, more manageable. It covers words starting from A to G (hence part 1 of 3). 

There have been some additions as well as squashed down commits.

### CODE REVIEW

**Comment by luzpaz** [comment]
not sure why codecov is failing

**Comment by luzpaz** [comment]
Please review

**Comment by luzpaz** [comment]
@larsoner any idea why the CI fails ?

**Comment by larsoner** [comment]
Codecov is just flaky

**Pull request merged**
