### PR TITLE
Add several spelling corrections

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by vikivivi** [comment]
1. Shall we move `traceback, tracebacks` (Python traceback) to `code` dictionary?
These are not a valid word in major dictionaries.
Valid word should be either `trace back, trace-back, backtrace`.
```text
tarceback->traceback
tarcebacks->tracebacks
```
2. Shall we add these additional misspell?
```text
distaces->distances, distastes,
maesurement->measurement
maesurements->measurements
maesuring->measuring
syntethically->synthetically
syntethics->synthetics
```
* https://github.com/search?q=distaces&type=code
* https://github.com/search?q=maesurement&type=code
* https://github.com/search?q=maesurements&type=code
* https://github.com/search?q=maesuring&type=code
* https://github.com/search?q=syntethically&type=code
* https://github.com/search?q=syntethics&type=code

**Comment by luzpaz** [comment]
@vikivivi done. see f2498d3

**Review by vikivivi — APPROVED** [review]
LGTM

**Comment by peternewman** [comment]
> 1. Shall we move `traceback, tracebacks` (Python traceback) to `code` dictionary?
>        These are not a valid word in major dictionaries.
>        Valid word should be either `trace back, trace-back, backtrace`.

No! @vikivivi the code dictionary is for words which are typos except when used in code, e.g. amin->main, as amin is a function in some language. But amin is never a valid English word.

If these are tripping up the CI because traceback isn't a valid correction, then we perhaps need another dictionary to manage things like that in.

**Pull request merged**
