### PR TITLE
Add several spelling corrections

### PR DESCRIPTION
**Pull request by adrien-berchet**

### CODE REVIEW

**Review by luzpaz — APPROVED** [review]

**Comment by vikivivi** [comment]
Just a quick check. Not so common misspellings except a few of them.
```text
fuertherst->furthest
fuerthest->furthest
fuerthrest->furthest
fuetherst->furthest
fuethest->furthest
fuethrest->furthest
```
* https://github.com/search?q=fuertherst&type=code  (0 hit)
* https://github.com/search?q=fuerthest&type=code  (0 hit)
* https://github.com/search?q=fuerthrest&type=code  (0 hit)
* https://github.com/search?q=fuetherst&type=code  (1 hit)
* https://github.com/search?q=fuethest&type=code  (8 hits)
* https://github.com/search?q=fuethrest&type=code  (0 hit)

```text
furetherst->furthest
furethrest->furthest
```
* https://github.com/search?q=furetherst&type=code  (0 hit)
* https://github.com/search?q=furethrest&type=code  (0 hit)

```text
furtherst->furthest
furthrest->furthest
```
* https://github.com/search?q=furtherst&type=code  (2,426 hits)
* https://github.com/search?q=furthrest&type=code  (122 hits)

**Comment by adrien-berchet** [comment]
Yeah, the one I actually encountered was `furtherst->furthest` but thought I could add a few others at the same time. I can remove the ones with 0 hit if you prefer.

**Comment by vikivivi** [comment]
> but thought I could add a few others at the same time. I can remove the ones with 0 hit if you prefer.

I personally suggest removing those 0 hit then force push. So that it will not penalise everyone using the tool by slowing down the check.

**Comment by adrien-berchet** [comment]
> I personally suggest removing those 0 hit then force push. So that it will not penalise everyone using the tool by slowing down the check.

Ok, I removed them and rebased on master.

**Comment by adrien-berchet** [comment]
Is there anything else to fix here?

**Review by vikivivi — APPROVED** [review]
LGTM

**Comment by luzpaz** [comment]
Thanks!

**Pull request merged**
