### PR TITLE
Remove bodgy->body as it's a valid word

### PR DESCRIPTION
**Pull request by peternewman**
https://www.lexico.com/en/definition/bodgie

### CODE REVIEW

**Comment by luzpaz** [comment]
on the fence about this one.

**Comment by peternewman** [comment]
> on the fence about this one.

How so, best case it should be disabled the same way as gonna is?

See also:
https://www.lexico.com/en/definition/bodge and https://www.collinsdictionary.com/dictionary/english/bodge

**Comment by peternewman** [comment]
Thoughts @larsoner ?

**Comment by larsoner** [comment]
Maybe for now disable how `gonna` is disabled until we get around to separating dictionaries into strict and loose?

**Comment by peternewman** [comment]
> Maybe for now disable how `gonna` is disabled until we get around to separating dictionaries into strict and loose?

Done

**Comment by peternewman** [comment]
Thanks @larsoner .

**Pull request merged**
