### PR TITLE
Improve the exclude-file help

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
I still cannot understand the meaning of this option.
What kind of content is expected to be in exclude-file?

I tried to make a file with a list of entries in form `path:line` like:

```
/home/milovidov/work/ClickHouse/base/common/iostream_debug_helpers.h:156
/home/milovidov/work/ClickHouse/base/common/preciseExp10.cpp:54
/home/milovidov/work/ClickHouse/base/common/preciseExp10.cpp:87
/home/milovidov/work/ClickHouse/base/common/preciseExp10.cpp:88
/home/milovidov/work/ClickHouse/base/glibc-compatibility/musl/COPYRIGHT:49
/home/milovidov/work/ClickHouse/base/glibc-compatibility/musl/COPYRIGHT:82
/home/milovidov/work/ClickHouse/base/glibc-compatibility/musl/COPYRIGHT:83
/home/milovidov/work/ClickHouse/programs/server/Server.cpp:359
/home/milovidov/work/ClickHouse/utils/github/query.py:144
```

But it does not work.

**Comment by peternewman** [comment]
@alexey-milovidov opening an issue will generally get a much faster response. It needs to be the contents of line 156 of /home/milovidov/work/ClickHouse/base/common/iostream_debug_helpers.h etc.

**Comment by alexey-milovidov** [comment]
I have finally figured out what does it mean.
If I remember correctly, the FILE should contain verbatim content of the lines that should be skipped.

But help is saying, simply:
`FILE with lines that should not be checked for errors or changed`

without a clue, how these lines should be specified in a FILE.

**Comment by peternewman** [comment]
> I had finally figured out what does it mean.
> If I remember correctly, the FILE should contain verbatim content of the lines that should be skipped.

Yes, the lines that shouldn't be checked for errors or changed.

> But the help is saying, simply:
> `FILE with lines that should not be checked for errors or changed`
> 
> without a clue, how these lines should be specified in a FILE.

Do you have any recommendations for how we could word it to make it less ambiguous?

**Comment by alexey-milovidov** [comment]
Something like this:

`FILE with lines that should not be checked for errors or changed (the FILE should contain full verbatim content of the lines to skip)`

PS. I understand that this is very minor usability issue :)

**Comment by peternewman** [comment]
> Something like this:
> 
> `FILE with lines that should not be checked for errors or changed (the FILE should contain full verbatim content of the lines to skip)`

Sounds like an improvement. Do you want to open a PR for that?

> PS. I understand that this is very minor usability issue :)

Every little helps!

**Pull request merged**
