### PR TITLE
Add several spelling corrections

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by vikivivi** [comment]
@luzpaz Both words `scrip` and `scrips` are valid spelling in aspell. They are also valid spelling in major online dictionaries like Cambridge, Oxford Learners, Longman, Lexico, Merriam-Webster, etc. Removing `scrip` and `scrips` would likely make the CI/CD checks to pass.

**Comment by luzpaz** [comment]
Maybe we can add them to 'rare' or alternate?

**Comment by vikivivi** [comment]
`dictionary_rare.txt` should be fine.

**Review by vikivivi — APPROVED** [review]
LGTM

**Pull request merged**
