### PR TITLE
Add variation typos of 'convert'

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by vikivivi** [comment]
@luzpaz Happy New Year. Would you mind adding entries tor the following?
Github code search for misspell of `convertibles` & `convertors` has ZERO hit.
`covnerter->converter`
`covnerters->converters`
`covnertible->convertible`
`covnertor->convertor`

**Comment by luzpaz** [comment]
Thanks, I will add soon.

**Review by peternewman — CHANGES_REQUESTED** [review]
Still pending @vikivivi 's suggestions

**Comment by peternewman** [comment]
> Still pending @vikivivi 's suggestions

These still aren't in your latest force push @luzpaz

**Comment by luzpaz** [comment]
> Github code search for misspell of `convertibles` & `convertors` has ZERO hit.

There are results for some of these off github. I believe i saw them on a forum. I think we should keep, nevertheless

**Review by bl-ue — APPROVED** [review]

**Comment by bl-ue** [comment]
Hmm, `convertor` is listed as a typo, but it's actually just a alternative to `converter`.  I'll remove that.

**Pull request merged**
