### PR TITLE
Add misspell: kubernetes

### PR DESCRIPTION
**Pull request by vikivivi**
New entry word: kubernetes
Typical code search URL:
  * https://github.com/search?q=kubenates&type=code
  * https://github.com/search?q=kubenernetes&type=code
  * https://github.com/search?q=kubenertes&type=code
  * https://github.com/search?q=kubenetes&type=code
  * https://github.com/search?q=kubenretes&type=code
  * https://github.com/search?q=kuberenetes&type=code
  * https://github.com/search?q=kuberentes&type=code
  * https://github.com/search?q=kuberetes&type=code
  * https://github.com/search?q=kubermetes&type=code
  * https://github.com/search?q=kubernates&type=code
  * https://github.com/search?q=kubernests&type=code
  * https://github.com/search?q=kubernete&type=code
  * https://github.com/search?q=kuberntes&type=code

### CODE REVIEW

**Review by peternewman — APPROVED** [review]
LGTM

**Review by peternewman — CHANGES_REQUESTED** [review]
Actually can you capitalise the RHS as it's a proper noun please.

**Comment by vikivivi** [comment]
@peternewman Capitalised done.

**Review by peternewman — APPROVED** [review]
Thanks @vikivivi

**Pull request merged**
