### PR TITLE
Remove strange typos containing special characters

### PR DESCRIPTION
**Pull request by bl-ue**

### CODE REVIEW

**Review by peternewman — COMMENTED** [review]
Any reason why you want these removed? I assume they didn't just get added for fun!

**Comment by bl-ue** [comment]
I removed them because they're quite odd, and they seem really specific to whomever made them in the first place.  They're annoying because they make it _appear_ as though the dictionary is not ordered alphabetically, and finally I reasoned that we should have some sort of system to remove diacritics from from words in source files before checking them, because currently there's only a few select words (based off of `contain` and `evaluate`) that get checked and corrected with these special characters.

**Comment by peternewman** [comment]
> I removed them because they're quite odd, and they seem really specific to whomever made them in the first place.

Don't all dictionary entries start off like that, or at least the more niche ones like say octothope? :wink: 

> They're annoying because they make it _appear_ as though the dictionary is not ordered alphabetically

That seems a fairly minor thing, I far more regularly fail to sort it alphabetically when adding stuff manually.

> and finally I reasoned that we should have some sort of system to remove diacritics from from words in source files before checking them, because currently there's only a few select words (based off of `contain` and `evaluate`) that get checked and corrected with these special characters.

That's very hard, especially for the é given words like café.

I really think we should keep these in place until that system exists, which could start off with the simple mapping of checking someone hasn't used:
https://www.fileformat.info/info/unicode/char/0441/index.htm

In place of any c's. 

Although that's almost a separate tool to codespell, as ideally it wants a full dictionary on the right (not just codespell's curated one) and to try substituting any of those characters for a c and see if they produce a valid English word. Perhaps it could be an optional extension though.

**Comment by bl-ue** [comment]
I don't really think they should be in here, but... 🤷🏻‍♂️

**Pull request closed without merging**
