### PR TITLE
dictionary_rare: add unsecure->insecure

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by larsoner** [comment]
I'm on the fence on this one. Especially since `codespell` is ideally for code, and `unsecure` is a fairly standard computing term, even `rare` seems like it might not be right (it probably won't actually be that rare for downstream users).

**Comment by waldyrious** [comment]
Happy to close this PR if you prefer not to add it. I don't have a strong opinion on the matter. I was myself not familiar with "unsecure" when I bumped into it, and at first thought it was a typo, then I figured that [Wiktionary declares it](https://en.wiktionary.org/wiki/unsecure) a rare spelling of "insecure", hence this PR.

**Review by bl-ue — APPROVED** [review]
+1 for putting in it rare — I've never even seen it before. (only `insecure`).  I'll merge this old PR in a week if there's no objections by then.

**Comment by larsoner** [comment]
"unsecured debt," is a common phrase in lending, but I agree even that form of unsecure would be comparatively rare enough to go in rare

**Comment by bl-ue** [comment]
Thank you @waldyrious :D

**Pull request merged**
