### PR TITLE
MAINT: Remove Python 3.5 support

### PR DESCRIPTION
**Pull request by bl-ue**
#1946 & https://github.com/codespell-project/codespell/pull/1657#issuecomment-684155941

### CODE REVIEW

**Comment by bl-ue** [comment]
Hmm, https://github.com/codespell-project/codespell/blob/57bdd34ea183e3e6830b91ec5370ed3ea6c69d55/.travis.yml#L11.  Do we still use Travis or can I just delete `.travis.yml` entirely?

**Comment by larsoner** [comment]
Yeah, let's just delete it

**Comment by bl-ue** [comment]
Done @larsoner 🗑️

**Comment by larsoner** [comment]
Thanks @bl-ue

**Pull request merged**
