### PR TITLE
Add vulnerabuility and variants

### PR DESCRIPTION
**Pull request by cfi-gb**
See e.g.:

https://github.com/search?q=Vulnerabuility&type=Code
https://github.com/search?q=%22vulnerabule%22&type=Code

I took the chance to make all existing "vulnerabilit(y|ies)" corrections uppercase.

### CODE REVIEW

**Comment by luzpaz** [comment]
> I took the chance to make all existing "vulnerabilit(y|ies)" corrections uppercase.

Please don't. `codespell` corrects words in the case it finds them. There are plenty of usecases where they don't need to capitalized and it could be very irritating that codespell makes that decision arbitrarily. Please revert the uppercasing.

**Comment by cfi-gb** [comment]
@luzpaz Thanks for the remark. This seems to me somehow in contradiction to what @peternewman had requested in https://github.com/codespell-project/codespell/pull/734 in the past.

That's why i had created https://github.com/codespell-project/codespell/issues/737 to have a fixed guideline on this topic.

**Comment by luzpaz** [comment]
either myself or you have misunderstood something here. `Microsoft` is a name and therefore falls in to that gray area of capitalization (I say gray because sometimes people don't want such words capitalized but nvm). You current PR for variations on the word 'vulnerable' doesn't fit that naming classification, AFAICT. Unless I'm missing something

**Comment by cfi-gb** [comment]
> Microsoft is a name and therefore falls in to that gray area of capitalization (I say gray because sometimes people don't want such words capitalized but nvm)

Understood. So that could be perfectly as part of the guideline requested in https://github.com/codespell-project/codespell/issues/737.

**Comment by cfi-gb** [comment]
Reverted the capitalization in 5561d1cb4e63fe82fb2ef732940fbdfd96e6fc4e

**Comment by peternewman** [comment]
Yeah I'd only asked for Microsoft to be capitalised because it's a name. If we have that bit of the dictionary correct, we can in future add an option to use or ignore the case of the dictionary (depending on if you're writing e.g. code or documentation.

**Pull request merged**
