### PR TITLE
Add a pre-commit hook definition to run codespell

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by larsoner** [comment]
I have never used this before. I looked only briefly at the docs

https://pre-commit.com/

Is the purpose of adding the file to `codespell`'s repo just to provide a template for other git repos that want to use codespell as a pre-commit hook? Or is there more to i?

**Comment by marco-c** [comment]
> Is the purpose of adding the file to codespell's repo just to provide a template for other git repos that want to use codespell as a pre-commit hook? Or is there more to i?

Yes, that's it. I've created a temporary repository to do it at https://github.com/marco-c/pre-commit-codespell, but I'm going to remove it if this PR is merged. Here's an example usage: https://github.com/mozilla/bugbug/pull/411.

Here's another example of pre-commit hook definition, for black: https://github.com/python/black/blob/master/.pre-commit-hooks.yaml.

**Comment by larsoner** [comment]
Great, thanks!

**Comment by asottile** [comment]
Adding this to the website -- thanks all! https://github.com/pre-commit/pre-commit.github.io/pull/237

**Pull request merged**
