### PR TITLE
Remove parameterizes->parametrizes

### PR DESCRIPTION
**Pull request by int-y1**
They're both correct.

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
**Dictionaries**

* Cambridge: missing
* Oxford; missing from Oxford Learner's Dictionaries, but according to [Is “parameterization” or “parametrization” correct when describing which parameters describe a statistical model?](https://sites.bc.edu/answerwall/2019/08/15/is-parameterization-or-parametrization-correct-when-describing-which-parameters-describe-a-statistical-model/) both “parameterization” and “parametrization” are in the Oxford Dictionary:
  > The Oxford English Dictionary recognizes both as options (and even parameterisation, imagine that!), so you can choose the one you like. I ran a Google Trends search to see usage of the 3 spellings over the past 15 years (bit.ly/Paramewhat); “parameterization” was the clear winner.
* Merriam-Webster: [parameterize](https://www.merriam-webster.com/dictionary/parameterize)
* Collins: [parameterize](https://www.collinsdictionary.com/dictionary/english/parameterize)
* American Heritage: [parameterize](https://www.ahdictionary.com/word/search.html?q=parameterize)
* Dictionary.com: [parameterize](https://www.dictionary.com/browse/parameterize)
* My [LanguageTool](https://languagetool.org) spell checker actually suggests parametrization → parameterization!

**Google Trends**

* parameterize: [8,510,000 hits](https://www.google.com/search?q=parameterize)
* parametrize: [3,640,000 hits](https://www.google.com/search?q=parametrize)
* parameterise: [246,000 hits](https://www.google.com/search?q=parameterise)
* parametrise: [118,000 hits](https://www.google.com/search?q=parametrise)

**Comment by DimitriPapadopoulos** [comment]
Also, it's highly inconsistent that we have both:
```
parameterizes->parametrizes
paramterize->parameterize
```
but not:
```
parameterize->parametrize
parameterized->parametrized
parameterizing->parametrizing
```

**Review by DimitriPapadopoulos — APPROVED** [review]

**Comment by peternewman** [comment]
A bit late now, but I'd generally encourage moving it into rare in future, as we don't have a mechanism to stop it just getting re-added tomorrow currently!

**Comment by DimitriPapadopoulos** [comment]
It is by far the most common spelling, for this reason, I believe it cannot be moved to rare.

Perhaps it should be added to the aspell dictionary instead.

**Pull request merged**
