### PR TITLE
Add wee->we

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
Not sure why Travis is failing: 
```
  File "/home/travis/venv/lib/python2.7/site-packages/docutils/utils/__init__.py", line 21, in <module>
    import docutils.io
  File "/home/travis/venv/lib/python2.7/site-packages/docutils/io.py", line 348
    (self.destination.mode, mode)), file=self._stderr)
                                        ^
SyntaxError: invalid syntax
The command "python setup.py check --restructuredtext --strict" exited with 1.
```
Source: https://travis-ci.org/codespell-project/codespell/jobs/561689610#L467-L473

**Comment by larsoner** [comment]
`wee` is a legit word, @peternewman did we decide to include these or no?

**Comment by peternewman** [comment]
> `wee` is a legit word, @peternewman did we decide to include these or no?

I really don't think we should in the main dictionary. To the extent I've started a Travis check in https://github.com/codespell-project/codespell/pull/1142 to catch such things. I proposed there should be an additional "strict" dictionary which you could optionally load which has things like this.

**Comment by peternewman** [comment]
Surely this should be in rare as part of #1142 ?

**Comment by peternewman** [comment]
It is now.

**Pull request merged**
