### PR TITLE
python heap sort added

### PR DESCRIPTION
**Pull request by khemrajshrestha471**

### CODE REVIEW

**Comment by luzpaz** [comment]
Can we remove hacktoberfest tags from the repo ? @larsoner 

This is getting ridiculous

**Comment by luzpaz** [comment]
``

**Comment by larsoner** [comment]
Done

**Comment by khemrajshrestha471** [comment]
Hello!

How and why my PR got spam labels?

**Comment by luzpaz** [comment]
@khemrajshrestha471 maybe due to garbage PRs that only serve to beef up your stats and in the process spam legit repositories and waste the time of volunteers ?

**Comment by luzpaz** [comment]
@khemrajshrestha471 reported to github

**Pull request closed without merging**
