### PR TITLE
chore(license): update to use spdx id

### PR DESCRIPTION
**Pull request by chenrui333**
it would be good to use spdx license ID to avoid confusion.

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
I agree that is clearer, but the reality is that the license for the Python module and the dictionaries are not the same. See https://github.com/codespell-project/codespell/issues/2682. I think we'd better spend time on explaining that complexity, instead of over-simplifying.

**Comment by DimitriPapadopoulos** [comment]
@larsoner I will let you decide on this one. Either over-simplify and use [SPDX](https://spdx.org/licenses/) identifiers as described in [PEP 639](https://peps.python.org/pep-0639/) (licenses had been left out of [PEP 621](https://peps.python.org/pep-0621/) on purpose to let a future PEP specify support for [SPDX](https://spdx.org/licenses/) identifiers).

**Comment by chenrui333** [comment]
based on my observations of this license declaration, some folks intend to do the exhausted acknowledgements, some folks just do it for the project itself. Either way, I think this change would be a good move (maybe part of the series of changes)

**Comment by larsoner** [comment]
To me this is just using a different (better, more standard) name, so +1 from me. I know `grayskull` for example does SPDX matching so this might help some people/tools

**Review by larsoner — APPROVED** [review]

**Pull request merged**
