### PR TITLE
Remove redundant linting CI workflows handled by pre-commit.ci

### PR DESCRIPTION
**Pull request by kurtmckee**
This PR removes the black and ruff CI workflows that are now run by pre-commit.ci.

One note: there's a `ruff-annotation` job in `codespell-private.yml`; I'm not sure if this should be removed as well.

### CODE REVIEW

**Comment by kurtmckee** [comment]
It appears that the black and ruff workflows are configured as "required". If this PR merges, some repo settings may need to be modified.

**Comment by larsoner** [comment]
I think we shouldn't need the `ruff-annotation` run either because `pre-commit.ci` should push fixes automatically for people

**Comment by larsoner** [comment]
... and hopefully we can also get rid of the separate `mypy` run

**Review by DimitriPapadopoulos — APPROVED** [review]

**Comment by DimitriPapadopoulos** [comment]
@larsoner I cannot merge because of the missing GitHub workflows. And I would like you to have a look any way.

**Comment by larsoner** [comment]
Thanks @kurtmckee !

**Pull request merged**
