### PR TITLE
Add deault: -> default: to dictionary

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by luzpaz** [comment]
@peternewman I haven't tested this, but does codespell not differentiate a string that ends with a colon ?

**Comment by luzpaz** [comment]
@kianmeng this PR is unnecessary, see results of this test: 

```shell
$ echo "deault" | codespell -
1: deault
        deault ==> default

$ echo "deault:" | codespell -
1: deault:
        deault ==> default
```

**Comment by kianmeng** [comment]
@luzpaz I see. I just figured out the issue. I was running codespell 2.1.0, which don't catch the error.

```sh
$ codespell --version
2.1.0

$ echo "deault" | codespell -
$ echo "deault:" | codespell -
```
Switching to master branch resolved that:

```sh
$ codespell --version
2.2.dev0

$ echo "deault" | codespell -
1: deault
        deault ==> default
$ echo "deault:" | codespell -
1: deault:
        deault ==> default
```

**Comment by luzpaz** [comment]
hmm.. sorry. Didn't realize that was the case. 
Yea..it's time for an update 
@peternewman

**Pull request closed without merging**
