### PR TITLE
Add spelling corrections for validate and variants.

### PR DESCRIPTION
**Pull request by cfi-gb**
See e.g.:
- https://github.com/search?q=Invalidtion&type=code
- https://github.com/search?q=Validtion&type=code

plus the suggestions given by @vikivivi in:

https://github.com/codespell-project/codespell/pull/2302#issuecomment-1058738530

### CODE REVIEW

**Review by luzpaz — APPROVED** [review]

**Comment by vikivivi** [comment]
Shall we add these misspellings as well?
```text
invalidted->invalidated
invalidting->invalidating
validted->invalidated
validting->invalidating
```
* https://github.com/search?q=invalidted&type=code
* https://github.com/search?q=invalidting&type=code
* https://github.com/search?q=validted&type=code
* https://github.com/search?q=validting&type=code

**Comment by luzpaz** [comment]
ping @cfi-gb

**Comment by cfi-gb** [comment]
I have seen this question but don't have any opinion on that and thus kept silent as it also wasn't directed to me. It would need to be answered by some one else.

**Comment by vikivivi** [comment]
> I have seen this question but don't have any opinion on that and thus kept silent as it also wasn't directed to me. It would need to be answered by some one else.

@cfi-gb Shall we add these misspellings as well?
```text
invalidted->invalidated
invalidting->invalidating
validted->invalidated
validting->invalidating
```

**Comment by cfi-gb** [comment]
So some one else would need to say yes/no then and if there is a yes i can apply the changes. :+1:

**Comment by luzpaz** [comment]
Green light from me

**Comment by cfi-gb** [comment]
Thanks a lot for @vikivivi for the suggestion and @luzpaz for the green light / review. The additional words / corrections have been included in a newly pushed version of this MR and are ready for review.

**Review by luzpaz — APPROVED** [review]

**Review by peternewman — APPROVED** [review]

**Comment by peternewman** [comment]
> So some one else would need to say yes/no then and if there is a yes i can apply the changes. +1

Thanks @cfi-gb and feel free to be bold in future! Especially if it's just a variant of a typo you've found it's likely if you don't add them now, then someone else will in due course...

**Pull request merged**
