### PR TITLE
Remove the grave accent (`) from the default word regex

### LINKED ISSUE #2981: Default word regex and grave accent (`)
Why include the grave accent (**&#x0060;**) in the default word regex?

https://github.com/codespell-project/codespell/blob/2eeb8b992e7fec4940a12bdac5e8837f0ffd6c98/codespell_lib/_codespell.py#L31

This messes up Markdown checking, just for the sake of catching these two typos:
```
coulden`t->couldn't
woulden`t->wouldn't
```
These two fixes don't really make sense, we don't even catch the same typos with the apostrophe (**&#x0027;**) or acute accent (**&#x00B4;**), :
```
coulden't->couldn't
coulden´t->couldn't
woulden't->wouldn't
woulden´t->wouldn't
```

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Catching typos that contain a grave accent (**\`**) is a niche. I bet we miss more typos just in Markdown files than we detect typos containing a grave accent (**\`**) in all files.

Additionally, this restores compliance with the documentation:
https://github.com/codespell-project/codespell/blob/2eeb8b992e7fec4940a12bdac5e8837f0ffd6c98/codespell_lib/_codespell.py#L404-L407

Use plural in the above help message:
	`is` → `are`

Fixes #2981.

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
@peternewman @larsoner Any suggestions or opinion on this one?

**Comment by larsoner** [comment]
> @peternewman @larsoner Any suggestions or opinion on this one?

Can you change a test in this PR that fails on `master` but passes in this PR to ideally illustrate the use case that works now but didn't before?

**Comment by DimitriPapadopoulos** [comment]
I have added a test that fails on `master` in [`grave_test`](https://github.com/DimitriPapadopoulos/codespell/tree/grave_test) (#2995).

I have rebased this branch [`grave`](https://github.com/DimitriPapadopoulos/codespell/tree/grave) onto [`grave_test`](https://github.com/DimitriPapadopoulos/codespell/tree/grave_test), the test passes.

**Comment by larsoner** [comment]
Seems like a pretty clear improvement to me! Let's give it a shot

**Pull request merged**
