### PR TITLE
Add several spelling corrections

### PR DESCRIPTION
**Pull request by luzpaz**
Related upstream PR: https://github.com/mumble-voip/mumble/pull/5540

### CODE REVIEW

**Comment by vikivivi** [comment]
I think the checks failed because suggested word is actually a misspell in another entry.
```text
receivs->recieves
repostories->respositories
```
Please help to correct these entries. Most major dictionaries use `built-in` rather than `buildin`.
```text
builting->building, built-in,
receivs->receives
repostories->repositories
```
Shall we add these additional misspells?
```text
correespondence->correspondence
correespondences->correspondences
correespondent->correspondent
depreates->deprecates
dequed->dequeued
deques->dequeues
namaed->named
reigons->reigns, regions,
togled->toggled
```
* https://github.com/search?q=correespondence&type=code
* https://github.com/search?q=correespondences&type=code
* https://github.com/search?q=correespondent&type=code
* https://github.com/search?q=depreates&type=code
* https://github.com/search?q=dequed&type=code
* https://github.com/search?q=deques&type=code
* https://github.com/search?q=namaed&type=code
* https://github.com/search?q=reigons&type=code
* https://github.com/search?q=togled&type=code

**Comment by peternewman** [comment]
> I think the checks failed because suggested word is actually a misspell in another entry.
> 
> ```
> receivs->recieves
> repostories->respositories
> ```

They don't appear to be present, but aren't valid words, so please add them as typos.

**Comment by luzpaz** [comment]
> They don't appear to be present, but aren't valid words, so please add them as typos.

They are in e67416526827f8636b64ba94f343337e9fe58f61  
All checks have passed. Should be green light to merge

**Comment by vikivivi** [comment]
> > I think the checks failed because suggested word is actually a misspell in another entry.
> > ```
> > receivs->recieves
> > repostories->respositories
> > ```

> They don't appear to be present, but aren't valid words, so please add them as typos.

They do appear to be present in my local master branch which is the same and in sync with remote/master.
```sh
$ git branch -vv
* master cf7ee138 [origin/master] Merge pull request #2258 from cfi-gb/add_protect_corrections
$ git rev-parse HEAD
cf7ee138d04f76377a0ab308236dd7787e69b504
```
Searching the original proposed suggestion which is already a misspell in dictionary.txt (Line 25081, 26566)
```
$ grep -rn recieves codespell_lib/data/
codespell_lib/data/dictionary.txt:25081:recieves->receives
$ grep -rn respositories codespell_lib/data/
codespell_lib/data/dictionary.txt:26566:respositories->repositories
```
* https://github.com/codespell-project/codespell/blob/cf7ee138d04f76377a0ab308236dd7787e69b504/codespell_lib/data/dictionary.txt#L25081-L25081
* https://github.com/codespell-project/codespell/blob/cf7ee138d04f76377a0ab308236dd7787e69b504/codespell_lib/data/dictionary.txt#L26566-L26566

**Review by peternewman — APPROVED** [review]

**Pull request merged**
