### PR TITLE
Reverse backwards rule parameterizes->parametrizes

### PR DESCRIPTION
**Pull request by warmsocks**
Fix backwards rule, which replaces correctly spelled 'parameterizes' with an incorrect spelling

### CODE REVIEW

**Comment by luzpaz** [comment]
@warmsocks please rebase, thx

**Comment by skangas** [comment]
@warmsocks Friendly ping.

**Comment by DimitriPapadopoulos** [comment]
`renable->re-enable` is OK.

**Comment by DimitriPapadopoulos** [comment]
Please rebase. I think this rule has been removed any way.

See [Is “parameterization” or “parametrization” correct when describing which parameters describe a statistical model?](https://sites.bc.edu/answerwall/2019/08/15/is-parameterization-or-parametrization-correct-when-describing-which-parameters-describe-a-statistical-model/)
> The Oxford English Dictionary recognizes both as options (and even parameterisation, imagine that!), so you can choose the one you like. I ran a Google Trends search to see usage of the 3 spellings over the past 15 years (bit.ly/Paramewhat); “parameterization” was the clear winner.

Indeed, the most common spelling appears to be `parameterize` (UK `parameterise`), but `parametrize` (UK `parametrise`) appears to be acknowledged as an alternative spelling:
* [Collins Cobuild](https://www.collinsdictionary.com/dictionary/english/parameterize)
  * `parameterise` in British english, `parameterize` in American English
  * also `parametrise`/`parametrize`
  * derived noun: `parameterization`
* [Merriam-Webster](https://www.merriam-webster.com/dictionary/parameterize)
  * `parameterize`, or `parametrize`
  *  `parameterization`, or `parametrization`
  *  also `-ed` and `-ing`: `parameterized`/`parametrized` and `parameterizing`/`parametrizing`

**Google hits**
* noun
  * `parameterization` [32,200,000](https://www.google.com/search?q=parameterization) / `parameterisation` [1,350,000](https://www.google.com/search?q=parameterisation)
  * `parametrization` [11,900,000](https://www.google.com/search?q=parametrization) / `parametrisation` [439,000](https://www.google.com/search?q=parametrisation)
* verb
  * `parameterize` [9,520,000](https://www.google.com/search?q=parameterize) / `parameterise` [219,000](https://www.google.com/search?q=parameterise)
  * `parametrize` [3,100,000](https://www.google.com/search?q=parametrize) / `parametrise` [105,000](https://www.google.com/search?q=parametrise)

Perhaps related fixes should be removed altogether.

In any case:
* any rule should include the derived noun in addition to the verb itself with `-ed` and -`ing`
* what about UK vs. US spellings?

Current fixes are a mess and should be fixed consistently:
```
paramterization->parametrization, parameterization,
paramterize->parameterize
reparamterization->reparameterization
```

**Comment by DimitriPapadopoulos** [comment]
Replaced by #2648.

**Pull request closed without merging**
