### PR TITLE
Another suggestion

### PR DESCRIPTION
**Pull request by gforcada**
While reviewing some code I noticed this typo on a comment 😄

### CODE REVIEW

**Review by DimitriPapadopoulos — APPROVED** [review]

**Comment by DimitriPapadopoulos** [comment]
Could you please rebase against the latest _master_ branch, in order to fix the CI issues?

**Comment by DimitriPapadopoulos** [comment]
Actually, `bettr` could also be a typo of `bettor`.

**Comment by gforcada** [comment]
@DimitriPapadopoulos yes, no problem, and thanks for the `bettor` suggestion, never heard of that word until today 😄

**Comment by gforcada** [comment]
Oh, thanks! 🙇🏾  you already did all the work 🪄 🍀

**Comment by DimitriPapadopoulos** [comment]
In the meantime, I updated and merged from the web interface. Thank you for your contributions.

**Pull request merged**
