### PR TITLE
StenographyEncoding

### PR DESCRIPTION
**Pull request by MadMax1311**

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
@MadMax1311 Please STOP this!

**Comment by MadMax1311** [comment]
I know you code but please don't react like follish i am beginner so guide not react this type

**Comment by DimitriPapadopoulos** [comment]
@MadMax1311 If you need to learn, please don't do that on a **production** repository. Go away.

**Comment by MadMax1311** [comment]
Ok when you start you also beginner understand this thing on your mind

**Comment by DimitriPapadopoulos** [comment]
It is not problem to be a beginner. However, it is extremely rude to post nonsensical pull requests to **production** repositories like this one, wasting the time and attention of lots of persons just because you feel like "trying stuff". You have no excuse for this repeatedly rude behaviour.
Go away.

**Comment by MadMax1311** [comment]
Ok but don't react this type understand

**Comment by MadMax1311** [comment]
I understand this

**Pull request closed without merging**
