### PR TITLE
Return exit status in __main__.py

### LINKED ISSUE #3156: Exit status is always 0 when started as a Python module
When started as `python -m codespell_lib` codespell always exits with 0.

Is it intentional?

### PR DESCRIPTION
**Pull request by szepeviktor**
Fixes #3156

### CODE REVIEW

**Review by DimitriPapadopoulos — APPROVED** [review]

**Comment by DimitriPapadopoulos** [comment]
We have a `pre-commit` hook runs `ruff`, including `isort`-like rules.

**Comment by szepeviktor** [comment]
Should I swap the two imports?

**Comment by DimitriPapadopoulos** [comment]
Probably. Running `isort` (or `ruff` with the proper option) should do that for you, perhaps adding a newline if needed.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by DimitriPapadopoulos** [comment]
You're welcome, thank you for reporting and fixing this issue.

**Pull request merged**
