### PR TITLE
False positive complies->compiles

### PR DESCRIPTION
**Pull request by polluks**
form of "comply"

### CODE REVIEW

**Comment by peternewman** [comment]
Hi @polluks ,

Thanks for this, please see the discussion in #2273 , essentially the whole rare dictionary is potential false positives, you can always turn it off if you'd prefer.

**Comment by polluks** [comment]
I see.

**Comment by sed-i** [comment]
Today suddenly started complaining about  `./LICENSE:128: complies ==> compiles`.
How do I disable the rares dictionary? Afaict it's not documented.

**Comment by peternewman** [comment]
> Now need to run with `codespell --builtin clear`.

Just ignoring that one word via an ignore list or ignore file would be the non-nuclear option here.

**Pull request closed without merging**
