### PR TITLE
Add spelling corrections for morphology

### PR DESCRIPTION
**Pull request by adrien-berchet**
https://github.com/search?q=morpholgy&type=code => 416 hits
https://github.com/search?q=morpholgies&type=code => 55 hits
https://github.com/search?q=morphlogy&type=code => 260 hits
https://github.com/search?q=morphlogies&type=code => 3 hits
https://github.com/search?q=mophology&type=code => 1.8k hits
https://github.com/search?q=mophologies&type=code => 13 hits

### CODE REVIEW

**Comment by adrien-berchet** [comment]
I think the CI fail is not related to this PR :thinking:

**Review by DimitriPapadopoulos — APPROVED** [review]

**Comment by DimitriPapadopoulos** [comment]
If you feel like it, you could add the same variations of `morphological`, `morphologist`/`morphologists`, and `morpheme`/`morphemes`.

**Comment by adrien-berchet** [comment]
Good point.
I checked and I found these hits:
https://github.com/search?q=morpholgical&type=code => 182 hits
https://github.com/search?q=morphlogical&type=code => 436 hits
https://github.com/search?q=morphlogist&type=code => 1 hit
https://github.com/search?q=morpholgist&type=code => 3 hits
https://github.com/search?q=morphlogists&type=code => 0 hit
https://github.com/search?q=morpholgists&type=code => 3 hits

So I added only the variations for `morphological` because the others are very rare. And the ones for `morpheme` return many false positive hits so I don't know how many real hits we could finf. But I can add more variations if you wish.

**Review by DimitriPapadopoulos — APPROVED** [review]

**Comment by DimitriPapadopoulos** [comment]
Thank you @adrien-berchet.

**Pull request merged**
