### PR TITLE
greyscale->grayscale

### PR DESCRIPTION
**Pull request by landfillbaby**
Just found this spelling inconsistency in my own code!

### CODE REVIEW

**Review by peternewman — APPROVED** [review]

**Comment by peternewman** [comment]
Thanks very much!

**Comment by peternewman** [comment]
Hmm, the test is failing because:
error 'greyscale' should be in aspell dictionaries (en_GB) for dictionary /home/runner/work/codespell/codespell/codespell_lib/tests/../data/dictionary_en-GB_to_en-US.txt

We'll have to ponder the best way to work around that...

**Comment by landfillbaby** [comment]
https://github.com/ropensci/hunspell/blob/master/inst/dict/en_GB.dic#L33086 ?

**Comment by DimitriPapadopoulos** [comment]
I have added `greyscale->grayscale` to the list of fixes missing from _aspell_, in the dedicated issue #2567.

Follow-up there if needed.

**Comment by landfillbaby** [comment]
i think you mean #2657

**Pull request closed without merging**
