### PR TITLE
Add several spelling corrections

### PR DESCRIPTION
**Pull request by larsoner**
Closes #1566

### CODE REVIEW

**Comment by pabs3** [comment]
How come you did this co-authored commit? I compared your commit with my original commit and there are no differences except to the commit message.

**Comment by larsoner** [comment]
I just did a `git cherry-pick` on top of latest `master` because it had some commits that made Travis happy, then pushed that to a new branch on my fork. I didn't feel comfortable rebasing or merging into your `master` branch (basis of your PR) and figured it would be faster than asking you to do either of those. Sorry if it messed up the history, I can ask for a rebase or merge next time instead if you prefer

**Comment by pabs3** [comment]
I think the approach that you took is fine since it is essentially
rebasing my commit locally before pushing but I was under the
impression that `git cherry-pick ...` preserves commit authorship?

-- 
bye,
pabs

https://wiki.debian.org/PaulWise

**Comment by larsoner** [comment]
The cherry pick 2d2ce36 above did preserve it, but then the squash and merge I did (I think that's what I did?) as 4f89573 appears not to have preserved it

**Pull request merged**
