### PR TITLE
Fix capitalisation of Portuguese to match other occurrences

### PR DESCRIPTION
**Pull request by lurch**

### CODE REVIEW

**Comment by sebweb3r** [comment]
There are a lot of words, that should be capital. From what I learned f.e. Asian has always to be capital. 
Same holds for names (f.e. Gaussian)

**Comment by lurch** [comment]
Okay, I've added those suggestions, and I'm happy to add any similar suggestions provided. But with almost 30,000 entries in the dictionary, I don't have time to search through it for "names that ought to be capitalised"! :stuck_out_tongue_winking_eye: 

Interestingly, https://en.wikipedia.org/wiki/Gauss_(unit) writes `gauss` with a lower-case `g` ? :shrug:

**Comment by sebweb3r** [comment]
I forgot the strange rule of the people doing the SI standard :-D

"They are printed in lower-case letters unless they are derived from a proper name, in which case the first letter is a capital letter" [1]

Most other words like Gaussian should be capital.

[1] https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9.pdf

**Comment by lurch** [comment]
So... does that mean that `gauss` or `Gauss` is correct? :shrug:  (obviously it wouldn't be the first time that Wikipedia is wrong :wink: )

**Comment by sebweb3r** [comment]
It means Gauss is the name and correct 90% of the times (since a lot of stuff is named after him). But if the unit gauss is meant, you should spell it small (even if some people don't do it)

**Comment by sebweb3r** [comment]
The easiest way to process this would propbably multiple merge requests. 
* names
* countries
* calendar stuff

otherwise it will grow big real quick. I can take over some of it, if you want.

**Comment by lurch** [comment]
> I can take over some of it

Please feel free! :smiley:

**Pull request merged**
