### PR TITLE
Fix underware with underwear

### PR DESCRIPTION
**Pull request by Gelma**

### CODE REVIEW

**Comment by luzpaz** [comment]
Nice catch. In that case can you also add `underware->underwear` please?

**Comment by Gelma** [comment]
Done. I'm going to push.

**Comment by peternewman** [comment]
> Done. I'm going to push.

We can't see it yet @Gelma ?

**Comment by Gelma** [comment]
> > Done. I'm going to push.
> 
> We can't see it yet @Gelma ?

The Luzpaz request is already pushed. I guess I pushed before write "I am going to push", so we have commit before commet.

Please check the commits. For me is complete.

**Comment by peternewman** [comment]
> The Luzpaz request is already pushed.

Apologies I misread it as a plural.

**Pull request merged**
