### PR TITLE
Move ba->by, be, as it's a name

### PR DESCRIPTION
**Pull request by peternewman**
As it's a name:
https://en.wikipedia.org/wiki/Ba_(given_name)

### CODE REVIEW

**Comment by luzpaz** [comment]
TBH, i think it's useless to have `ba` because I'm constantly needing to whitelist it.

**Comment by peternewman** [comment]
> TBH, i think it's useless to have `ba` because I'm constantly needing to whitelist it.

Well it will be disabled by default now its in names. But it is also a typo.

**Comment by peternewman** [comment]
Do you want to approve then @luzpaz ?

**Review by luzpaz — APPROVED** [review]

**Comment by luzpaz** [comment]
Sorry about that. Approved.

**Pull request merged**
