### PR TITLE
Add journalling->journaling to GB->EN dict

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by vikivivi** [comment]
My 2 cents opinion, I would suggest withdraw this PR.
`journalling` is not found in many major and reputable dictionaries.

It is also not found in these dictionaries.
aspell, hunspell, ispell, aoo-mozilla-en-dict, scowl/wordlist

The tests failed because it is not found in aspell dictionary.

https://www.google.com/search?q=journalling

https://www.lexico.com/definition/journalling
https://www.lexico.com/search?filter=en_dictionary&query=journalling
https://www.ldoceonline.com/dictionary/journalling
https://www.ldoceonline.com/spellcheck/english/?q=journalling
https://www.oxfordlearnersdictionaries.com/definition/english/journalling
https://www.oxfordlearnersdictionaries.com/spellcheck/english/?q=journalling

https://dictionary.cambridge.org/dictionary/english/journalling
https://dictionary.cambridge.org/spellcheck/english/?q=journalling
https://www.collinsdictionary.com/dictionary/english/journalling
https://www.dictionary.com/browse/journalling
https://www.dictionary.com/misspelling?term=journalling
https://www.merriam-webster.com/dictionary/journalling

https://www.macmillandictionary.com/us/dictionary/american/journalling
https://www.britannica.com/dictionary/eb/spelling/journalling
https://www.ahdictionary.com/word/search.html?q=journalling

https://www.definitions.net/definition/journalling
https://chambers.co.uk/search/?query=journalling&title=21st
https://thebestdictionary.com/definition/journalling
https://www.thefreedictionary.com/journalling
https://www.vocabulary.com/dictionary/journalling
https://en.wiktionary.org/wiki/journalling
https://www.wordhippo.com/what-is/the-meaning-of-the-word/journalling.html
https://www.wordreference.com/definition/journalling

**Comment by vikivivi** [comment]
> so should we just add it as an entry in to the main dictionary ?

I’m in agreement with with your suggestion.

**Comment by DimitriPapadopoulos** [comment]
@luzpaz Could you perhaps move it to main dictionary as suggested ad agreed (as far as I can tell)?

**Comment by DimitriPapadopoulos** [comment]
Actually, both `journalling`/ `journaling` are missing from most major and reputable dictionaries cited in https://github.com/codespell-project/codespell/pull/2371#issuecomment-1168594012, except [Collins](https://www.collinsdictionary.com/dictionary/english/journalling):
  > ### journalling
  > **in British English**
  > 
  > _or_ especially US **journaling**
  > **NOUN**
  > the practice of keeping a journal or diary, esp in order to express one's thoughts

I think journaling/journalling is mostly a technical term referring to operating systems and software in general. Its use in the sense of keeping a diary is anecdotal, hence its absence from major reputable dictionaries. From the [Wikitionary](https://en.wiktionary.org/wiki/journalling):
> #### Noun
>
> **journalling** ([countable](https://en.wiktionary.org/wiki/Appendix:Glossary#countable) and [uncountable](https://en.wiktionary.org/wiki/Appendix:Glossary#uncountable), plural [**journallings**](https://en.wiktionary.org/wiki/journallings#English))
> 1. _Alternative form_ of [**journaling**](https://en.wiktionary.org/wiki/journaling#English)

In the one major and reputable dictionary that has the word, `journalling` is flagged as a British variant and `journaling` as the only US spelling. Therefore, I tend to agree with the initial suggestion by @luzpaz.

**Review by DimitriPapadopoulos — APPROVED** [review]

**Comment by luzpaz** [comment]
@DimitriPapadopoulos feel free to merge when the time is right

**Comment by DimitriPapadopoulos** [comment]
@luzpaz We need to fix the _aspell_ bug(?) first. Can you have a look at #2933?

**Pull request merged**
